### ISSUE TITLE
Audio Support

### ISSUE THREAD

**Issue by divinemaredi** [am15h/tflite_flutter_plugin#46] opened 2020-10-14 12:03 UTC
Does this flutter package support audio models? (E.g. I'd like my app to listen to short commands and then execute a specific action based on the command)

**Comment by am15h** [comment] 2020-10-14 16:38
@divinemaredi You can use any `.tflite` model. You will need to write code for pre-processing and post-processing manually for now, i.e. converting raw data to bytes representation for input and converting bytes output data to a desirable form.

**Comment by divinemaredi** [comment] 2020-10-14 18:18
Thanks for the clarification! It's much appreciated.

**Comment by am15h** [comment] 2020-10-15 06:19
Thanks divinemaredi, Closing this as it is not an issue with the plugin, please feel to reopen if you face any challenges

**Closed by am15h** 2020-10-15 06:19 UTC

**Comment by nazdream** [comment] 2021-07-21 23:03
@am15h  Hi, I am trying to use https://teachablemachine.withgoogle.com/train/audio audio model with the package to count specific sound numbers in the audio from the microphone.

1) I wonder if it is possible to use a pre-trained audio model from https://teachablemachine.withgoogle.com/train/audio with the package or I need to create a custom one. 
2) I am trying to process real-time data from the microphone with the model, but I am getting this error. I am getting Uint8List from the microphone:
 _audioStream = _recorder.audioStream.listen((data) {
     print('data: $data');
      var output = [];
      _interpreter.run(data, output);
}
Getting this error when executing _interpreter.run function:

```
E/flutter (10616): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: failed precondition
E/flutter (10616): #0      checkState (package:quiver/check.dart:74:5)
E/flutter (10616): #1      Tensor.setTo (package:tflite_flutter/src/tensor.dart:146:5)
E/flutter (10616): #2      Interpreter.runForMultipleInputs (package:tflite_flutter/src/interpreter.dart:186:33)
E/flutter (10616): #3      Interpreter.run (package:tflite_flutter/src/interpreter.dart:157:5)
E/flutter (10616): #4      _AppState._initPlugin.<anonymous closure> (package:tf_test/main.dart:50:20)
E/flutter (10616): #5      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (10616): #6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (10616): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (10616): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (10616): #9      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (10616): #10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (10616): #11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (10616): #12     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (10616): #13     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (10616): #14     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (10616): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (10616): #16     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (10616): #17     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (10616): #18     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (10616): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (10616): #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (10616): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

I am not sure what the problem is and I can't find any info on the topic. Any feedback is highly appreciated.

 I am using this package version `tflite_flutter: ^0.9.0` and `sound_stream: ^0.3.0` to get Stream from the microphone.

**Comment by gfhjjk** [comment] 2022-12-02 09:43
> @divinemaredi You can use any `.tflite` model. You will need to write code for pre-processing and post-processing manually for now, i.e. converting raw data to bytes representation for input and converting bytes output data to a desirable form.

Pre processing means that audio cannot be used directly 
TensorAudio tensorAudio = TensorAudio.create(TensorAudioFormat.create(1, sampleRate), 377);

Do I need to write my own audio processing？
Thank you
