### ISSUE TITLE
W/FlutterEngine( 8943): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@17540cb) but could not find and invoke the GeneratedPluginRegistrant. Error connecting to the service protocol: failed to connect to 

### ISSUE THREAD

**Issue by GanZhiXiong** [am15h/tflite_flutter_plugin#14] opened 2020-04-14 02:49 UTC
```
Launching lib/main.dart on HUAWEI MT7 TL10 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
W/FlutterEngine( 8943): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@17540cb) but could not find and invoke the GeneratedPluginRegistrant.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:57991/4YEMNcZHU3A=/
```

**Comment by GanZhiXiong** [comment] 2020-04-14 02:55
device is Android 6.0

**Comment by am15h** [comment] 2020-04-14 05:24
Hi @GanZhiXiong, can you please confirm if this issue occurs only when using `tflite_flutter` and not without that. How can I reproduce this issue?

**Comment by GanZhiXiong** [comment] 2020-04-14 06:28
I downloaded the zip code, opened it in Android Studio, compiled it to an Android phone, and reported this error

**Comment by GanZhiXiong** [comment] 2020-04-14 06:32
I have another question. I'm not sure what your App is used for？
![image](https://user-images.githubusercontent.com/27394631/79193136-97f92500-7e5c-11ea-9585-7c82e837acf9.png)

**Comment by am15h** [comment] 2020-04-14 08:17
@GanZhiXiong This app text classifier model from TF Hub to classify a given text as positive (green) or negative(red). 
For ex:. Good->green, Bad->red.
You can find more info here https://www.tensorflow.org/lite/models/text_classification/overview.

**Comment by am15h** [comment] 2020-04-14 08:18
> I downloaded the zip code, opened it in Android Studio, compiled it to an Android phone, and reported this error
> 
> **No problem running in iOS**

Thanks for clarifying, I will check it out.

**Comment by am15h** [comment] 2020-04-19 07:50
Hi @GanZhiXiong, I think the problem is specifically with running on Android 6.0. Please try doing this,

1. Remove this line https://github.com/am15h/tflite_flutter_plugin/blob/master/example/pubspec.yaml#L24 in your local project.
2. `flutter pub get`
3. Comment out this https://github.com/am15h/tflite_flutter_plugin/blob/master/example/test/tflite_flutter_plugin_example_e2e.dart#L12 and https://github.com/am15h/tflite_flutter_plugin/blob/master/example/test/tflite_flutter_plugin_example_e2e.dart#L23 in your local project.
4. In tflite_flutter_plugin/example execute `sh install.sh` (If you haven't already as explained in [initial setup](https://github.com/am15h/tflite_flutter_plugin#initial-setup)).
5. In tflite_flutter_plugin/example execute `flutter clean`.
6. Now try running.

**Comment by am15h** [comment] 2020-05-06 16:36
Closing this issue. Feel free to reopen if error still persists.

**Closed by am15h** 2020-05-06 16:36 UTC
